# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: fabianstiehle.com
email: admin@fabianstiehle.com
description: > # this means to ignore newlines until "baseurl:"
  Life and technology.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://fabianstiehle.com" # the base hostname & protocol for your site
imgurl: "https://fabianstiehle.com/assets/img"
twitter_username: fastiehle
github_username:  fastiehle

# Build settings
markdown: kramdown
sass:
    sass_dir: _sass

plugins:
    #- jekyll-minifier

exclude: ['node_modules', 'src']
    
highlighter: rouge

# Outputting
permalink: /:title