# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: fabianstiehle.com
email: admin@fabianstiehle.com
description: > # this means to ignore newlines until "baseurl:"
  Writing about life and technology.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://fabianstiehle.com" # the base hostname & protocol for your site
imgurl: "http://fabianstiehle.com/assets/img"
twitter_username: fastiehle
github_username:  fastiehle
story_dir: story # affects _includes, assets, _sass

# Build settings
markdown: kramdown
sass:
    sass_dir: _sass

#gems:
#    - jekyll-minifier
    
highlighter: rouge

# Outputting
permalink: /:title